# Generated by Django 2.0.4 on 2018-04-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='image',
            field=models.ImageField(blank=True, upload_to='относительный каталог для файлов/', verbose_name='подпись'),
        ),
    ]
